### ISSUE TITLE
Please tag a release for distro packaging

### ISSUE THREAD

**Issue by ScrumpyJack** [dvehrs/podget#1]
Would you be kind enough to tag a release of podget so that it can be packaged?
Excellent script by the way, been using it for years

**Comment by dvehrs** [comment]
Thanks!

OK, I am tagging versions on my end before I upload them to Github and it's apparently not carrying over for some reason.  I'm using the format v0.7.9 for my tags, would that be acceptable for watching for packaging?  Or do you think it should be different?  Maybe spell out 'Version0.7.9"?

**Comment by fszymanski** [comment]
Most people use the v0.7.9 format.

**Comment by dvehrs** [comment]
OK, I think this thread has been open for comments long enough.  I've added a v0.7.9 tag to the current version of Podget in Github and will make a note to update it as I get to new versions.

Thanks for the help!
