### ISSUE TITLE
Feed filename renaming

### ISSUE THREAD

**Issue by markcs** [dvehrs/podget#13]
Hi!

I'm trying to download a feed with the following format:
`<enclosure url="https://api.soundcloud.com/tracks/271090958/stream?consumer_key=b259bac51a32ebe4d1c4a3a380501d27" type="audio/mp3" />`

The rss file is generated from here:
[http://sc2podcast.azurewebsites.net/podcast?user=cresultsfitness&keyword=&title=cresultsfitness](url)

This downloads the files with name 'consumer_key=b259bac51a32ebe4d1c4a3a380501d27'.  I get around all files being downloaded with this name by using OPT_FILENAME_RENAME_MDATE option.

Is there any way that podget can rename the files to the Title tag within the RSS feed and add an mp3 extension?

**Comment by dvehrs** [comment]
I can see why this would be desirable.  Unfortunately it's not possible with the way Podget currently works.  Podget works by extracting the enclosure tags and then parsing them for the URL.  So in the currently implementation there is no way to correlate a TITLE tag to the ENCLOSURE tag.  

Now there may be a way to do it but it would require of rewrite a large parts of Podget to process the feed file sequentially with each ITEM section parsed independent of the others.

I'm also unsure of how that method would affect how Podget handled other RSS or ATOM feeds.

OK, enough for the bad news.  Now for the good news.

I did a couple test runs with this feed and it seems that you found 50% of the answer for making this feed produce usable filenames.

We need to enable two options tags to prettify the filenames.  We need both OPT_FILENAME_LOCATION and OPT_FILENAME_RENAME_MDATE.

When we have them both enabled, the filename is changed.  First from what is held in the HTTP server response field for the LOCATION value and then the Modification date is added.

So if we make the changes to our serverlist and run 'podget -vvvv', for each item we will see something similar to:

```
ORIGINAL FILENAME:      stream?consumer_key=b259bac51a32ebe4d1c4a3a380501d27
MODIFIED FILENAME:      stream_consumer_key_b259bac51a32ebe4d1c4a3a380501d27
Downloading stream_consumer_key_b259bac51a32ebe4d1c4a3a380501d27 from https://api.soundcloud.com/tracks/186700853
    [ Progress meters disabled while using OPT_FILENAME_LOCATION ]
FILENAME CHANGE from stream_consumer_key_b259bac51a32ebe4d1c4a3a380501d27 to oX9NAEipjnUj.128.mp3
FILENAME CHANGE from oX9NAEipjnUj.128.mp3 to 20150118_14h55m_oX9NAEipjnUj.128.mp3
```

So the LOCATION tag may not give us a totally usable filename but it does give us the ".mp3".   And then the modification date makes it fairly easy to sort the filenames. 

While this is certainly not as good as using the TITLE, I hope it works until I can figure out something better.

**Comment by dvehrs** [comment]
OH, one last note.  I tested this with both the 'master' and 'dev' branches.  It works for both.

However, I'm working on some changes to cleanup and make the output a little prettier.  That implementation is in the 'dev' branch.    The above example was taken from the 'dev' branch output, the same output from the 'master' branch would look like:

```
ORIGINAL FILENAME:      stream?consumer_key=b259bac51a32ebe4d1c4a3a380501d27
MODIFIED FILENAME:      stream_consumer_key_b259bac51a32ebe4d1c4a3a380501d27
Downloading stream_consumer_key_b259bac51a32ebe4d1c4a3a380501d27 from https://api.soundcloud.com/tracks/186700853
    [ Progress meters disabled while using OPT_FILENAME_LOCATION ]
FILENAME LOCATION TESTS
SERVER RESPONSE FILE NONZERO SIZE
LOCATION_FILENAME: 'oX9NAEipjnUj.128.mp3'
FILENAME CHANGE from stream_consumer_key_b259bac51a32ebe4d1c4a3a380501d27 to oX9NAEipjnUj.128.mp3
FILENAME CHANGE from oX9NAEipjnUj.128.mp3 to 20150118_14h55m_oX9NAEipjnUj.128.mp3
PLAYLIST: Adding TEST/Results Fitness/20150118_14h55m_oX9NAEipjnUj.128.mp3 to /home/lowkey/NoBackups/POD/New-2016-07-07.r3.m3u
```

**Comment by DrAzraelTod** [comment]
you could use an extra script with i.e. ffprobe to read out file properties and rename files after they've been downloaded by podget

for example i use the following to display the metadata-titles, since some files are not really helpful named:

```
#!/bin/sh
for file in *
do
  title=`ffprobe 2> /dev/null -show_format $file | grep TAG:title= | cut -d '=' -f 2` &&
  printf "%$1s %s\n" $file "$title";
done;
```

**Comment by dvehrs** [comment]
That is an interesting idea.   I've been toying with using id3v2 to be able to automatically convert the genre on downloaded podcasts.  Far too many in my collection have genres that are inconsistent or make no sense.  I haven't come up with a good way to do it yet but ffprobe might give me another way to test what tags have been already set.  

Not sure that it will help much for this feed as they didn't set any tags on the item I randomly selected to test.

**Comment by markcs** [comment]
Thanks both for your suggestions.  

I had tried earlier to use the external program eye3D (much like ffprobe to fix up id3 tags), but unfortunately the stream does not include id3 tags, so it was not any help.  But I agree, that it would be a nice feature to have.

Dave, thanks for your suggestion of using both OPT_FILENAME_LOCATION and OPT_FILENAME_RENAME_MDATE.  I've now done this, and although the filenames are not pretty, at least they can now be played! 

Thanks for your suggestion.
