### ISSUE TITLE
Make category optional

### ISSUE THREAD

**Issue by ghost** [dvehrs/podget#19]
Would it be possible to make the category that's assigned to a podcast optional rather than mandatory, e.g. by specifying `-` as the category in the user's `CONFIG_SERVERLIST`?

`http://thelinuxlink.net/tllts/tllts.rss - The Linux Link` would then store the podcast directly in `DIR_LIBRARY/The Linux Link`.

**Comment by dvehrs** [comment]
I'm not sure that's possible as it exists.  Podget parses the items in the server list sequentially that are separated by spaces.  The only reason that the name can be multiple words is that it is the last item on the line.

Now we could change Podget to use CATEGORY and NAME keywords before each but that would break backwards compatibility and require everyone to manually update their serverlists.

Now, I will need to review my notes to see if I considered other alternatives but that is how I tend to use it.

**Comment by dvehrs** [comment]
OK, I think I might have found a 'hack' that effectively makes the category optional.  This has undergone very limited testing so it needs more, but making the category optional maybe a simple as simply using a single period (.) to represent the category.   Then the feed directory is created directly in the LIBRARY directory.

I'm not entirely happy with this solution but it does seem to prove that it is possible to make feeds without categories that do not require major rewrites.  The only surprising part is it took me this long to realize this would work.   

Wondering now if this should simply be added to the Serverlist instructions or if it might be better to create a keyword to use as the category when we want it to happen....

**Comment by dvehrs** [comment]
OK, I've added a check to the dev branch that looks for the category "No_Category" and treats it as if it were set to a single period (.).   This effectively gives two ways for category to be optional.  We'll see how it tests for the next release.

**Comment by dvehrs** [comment]
OK, on my limited collection of systems this tested well so I've merged it with the master branch and packaged it for release in the new 0.8.4 version.  

Any issues will have to be filed as new bugs.   Here's hoping there aren't any!  ;-P
