### ISSUE TITLE
Potential problem with OPT_DISPOSITION_FAIL and certain feeds

### ISSUE THREAD

**Issue by anon-anonymous** [dvehrs/podget#20]
I think there could be a problem with using the OPT_DISPOSITION_FAIL option with feeds whose enclosure items use the same filename for every item (e.g. feed: `http://rss.acast.com/naked_astronomy_podcast`, sample enclosure item: `http://rss.acast.com/naked_astronomy_podcast/eyes-on-the-sky-for-mercury/media.mp3`).

From what I can tell, using the OPT_DISPOSITION_FAIL option removes the downloaded file's URL from the COMPLETED log until the server responds with a useful 'filename=' tag, at which point the downloaded file gets renamed accordingly. The problem, however, arises as soon as a feed's enclosure items would result in the same filename and thus depend on this tag for being renamed to unique filenames. If these items' renaming gets "delayed" we end up with multiple files or one file that gets overwritten multiple times depending on Wget's options. Also, in both cases, as soon as there is a 'filename=' tag, a wrong file might get renamed.

I haven't had the chance to fully test this myself as I don't know of any suitable feed/server for this problem to arise, but I have stumbled upon one feed that contains one item whose server response lacks the 'filename=' tag in contrast to all the other items in that feed (feed: `http://rss.acast.com/weirdtalesandtheunexplainable`, enclosure item without 'filename=' tag: `http://media.acast.com/weirdtalesandtheunexplainable/-4-weird-media/media.mp3`). However, only one item is still too few to thoroughly test this.

**Comment by dvehrs** [comment]
That is exactly how it is designed to function.  It does that because some feeds will intermittently provide filenames and this allows Podget to retry each item until it has a name.  It was mostly tested with feeds that have unique but unfriendly names.  If the feed tries to use the same name for each, you probably want to look into another option first.  Maybe one of the FILENAME_FORMATFIXes or OPT_FILENAME_RENAME_MDATE would make the names unique.

**Comment by anon-anonymous** [comment]
Thanks for the clarification and pointing me in the right direction. Using a separate configuration with `FILENAME_FORMATFIX4` enabled should do the trick for these feeds.
