### ISSUE TITLE
[request] Prevent tabs after Feed name in serverlist from being used in directory name [with patch]

### ISSUE THREAD

**Issue by Corin-EU** [dvehrs/podget#21]
In my podget serverlist, I have always used tabs rather than spaces to separate the fields and until now have not had any problems, eg

     #.............................................................................#
     #
     # Science
     #
     #.............................................................................#
     #
     https://podcasts.vpr.NET/eye-on-the-night-sky                           Science         Eye_On_The_Night_Sky
     #
     http://rss.acast.COM/pulseoftheplanet                                   Science         Pulse_Of_The_Planet
     #
     http://www.kqed.ORG/rss/questaudio.xml                                  Science         QUEST_Science_Radio
     #
     http://feeds.wnyc.ORG/radiolab                                          Science         Radiolab
     #
     https://www.houstonpublicmedia.ORG/podcasts/engines-of-our-ingenuity    Science         The_Engines_Of_Our_Ingenuity
     #
     #*---------------------------------------------------------------------------*#

"Pulse Of the Planet" have recently changed their file naming format from a date named podcast to a "{topic directory}/media.mp3" format, obviously to prevent downloads of the same ageing podcasts which they now keep repeating on a regular basis instead of producing new material.

Thus it is now necessary to use the  OPT_FILENAME_LOCATION   OPT_FILENAME_RENAME_MDATE options to ensure that the downloaded file (if not recorded as  previously saved) is not named media.mp3 and overwritten on each download.

The issue that has become evident is that if tabs are also used to separate these fields after the feed name field , then the feed name directory is set to "feed_nameTAB" and a new directory with the tab character in the name is created for storing the download.

This issues comes from the lines beginning at 1884

            # Remove any residual trailing spaces from ${FEED_NAME}
            while (( $(expr "${FEED_NAME}" : ".*[ ]\+$") > 0 )); do
                FEED_NAME=${FEED_NAME%[ ]*}
            done

            # Remove any residual leading spaces from ${FEED_NAME}
            while (( $(expr "${FEED_NAME}" : "[ ]\+.*$") > 0 )); do
                FEED_NAME=${FEED_NAME#[ ]*}
            done

These lines can simply replaced with one sed line (without the ineffecient character by character loops and IMHO is easier to understand than decrypting BASH environmental variable special characters) which takes care of whitespace be it spaces, tabs, or a mixture of both

            # Remove any leading or trailing whitespace from FEED_NAME
            FEED_NAME=$(echo -n "${FEED_NAME}" | sed -e \
                        's|[[:space:]]*\([^[:space:]]*\)[[:space:]]*|\1|')

I have just applied this change to the podget script and run a download session -- nothing is broken and there is no {creation/use of} a feed name directory with trailing tab character(s).

From the podget verbose 3 log -

     ORIGINAL FILENAME:      media.mp3
     MODIFIED FILENAME:      media.mp3
     Downloading media.mp3 from http://media.acast.com/pulseoftheplanet/christmas-bonfires---construction
      [ Progress meters disabled while using OPT_FILENAME_LOCATION ]
     FILENAME CHANGE PREVENTED [ qMW7nIRMYf2TwkbjRmitJQ.mp3 already exists ]
     FILENAME CHANGE from media.mp3 to 20161216_18h12m_media.mp3
     PLAYLIST: Adding Science/Pulse_Of_The_Planet/20161216_18h12m_media.mp3 to /srv/archive/Media/Podcasts/Podcasts-2016-12-24.m3u

[podget.patch.txt](https://github.com/dvehrs/podget/files/671969/podget.patch.txt)

**Comment by dvehrs** [comment]
OK, I've been thinking about this for a few days and you definitely found a bug.

Now I partially agree with your solution and I partially don't.

I agree the while loops need to go.

However, I disagree that a subshell with sed is the appropriate solution.  It may be more readable than using bash parameter substitution but it's a subshell.

Instead of a subshell, what I am currently testing is replacing the two while loops with the below:
```
# Remove any residual leading whitespaces from ${FEED_NAME}
FEED_NAME="${FEED_NAME#"${FEED_NAME%%[![:space:]]*}"}"

# Remove any residual trailing whitespace from ${FEED_NAME}
FEED_NAME="${FEED_NAME%"${FEED_NAME##*[![:space:]]}"}"
```

Now admittedly this is less easy to read but it's 100% BASH.

I've also pushed the version I'm testing to the 'dev' branch if you'd care to test it.  So far it appears to be working.

**Comment by Corin-EU** [comment]
Thank you for investigating this issue.

I downloaded the latest branch "dev" version and installed that podget shell script and have been running it continously for several days now resulting in the download of POTP and numerous other feeds.

The problem of a directory being created with a tab in the name is no more and no other problems have appeared, so all is looking very good for the latest revision of the script.
