### ISSUE TITLE
How do you download from an rss feed with the newest items on the bottom?

### ISSUE THREAD

**Issue by Oflameo** [dvehrs/podget#22]
I found an rss feed where the newest items are on the bottom instead of the top. It was this one http://feeds.feedburner.com/FreedomainRadioVolume6?format=xml. Unlike a normal feed like this one http://www.blogtalkradio.com/ghost/podcast, it will download the oldest three podcast if I try to call it with `--recent 3`. Is there a way to compensate for this?

**Comment by dvehrs** [comment]
OK, there are two ways to handle this.  The old way and the new way.

By default, Podget assumes that each feed will be listed in descending order (newest first).  The old method to deal with this was manual and took a few steps.

OLD WAY (Manual way):
1.  First we want to mark all the older items as 'already downloaded' without actually downloading them.  To do so, we run podget with the --recent (or -r) option.  Like so:  podget --recent 1

This will download the first item of the feed and then mark every other item as already downloaded.   Then the next time you run the feed, it will only download any newly added items.

2.  If there are a few of the newer items at the end of the list that you want to download, open your LOG_COMPLETE (by default filename "done") and remove a few of the last items from the feed you just downloaded with '--recent'.  This may require paging down the list to get to the last few of the feed.

NEW WAY (Automated way):

In your serverlist file, for a feed that you need to add one option to the server description line to let Podget know that it is in reverse order.  So for the FreedomainRadio podcast, the line in your serverlist file would look like:

```
http://feeds.feedburner.com/FreedomainRadioVolume6?format=xml    TEST-Oflameo   FreedomainRadio  OPT_FEED_ORDER_ASCENDING
```

Now if we run "podget --recent 3", we will see that it downloads the last three items on the list and marks the rest as already downloaded.  And you can use as many or as few for --recent as you like.  Maybe you want 5 or just 1 then all new after today will download.  

Now this option only has an effect when used in combination with --recent.  The order that the items are listed is effectively irrelevant if you want them all to be downloaded.
