### ISSUE TITLE
Numbering prefix and post-success actions

### ISSUE THREAD

**Issue by lardconcepts** [dvehrs/podget#23]
Hi Dave,

This is great, particularly the ability to download passworded podcasts where others fail. Thank you!

However, I was wondering  if you would consider adding an option to run a post-success job, so that if a new podcast update was detected and downloaded, another script could then be called.

The other thing is that I know there is an option to suffix files, but I would love to be able to number-prefix files, in their correct order. 

I think both would be useful to others too.

If it helps, I am more than willing to make a donation to speed this along.
Would you like me to contact you on your email address?

Thank you.

**Comment by dvehrs** [comment]
Interesting ideas and we may have certain tools in place already that might be usable to address them.

For the first (calling another script at completion), this was something that we looked at before and it was difficult to restrict function of the follow-up script to just the newly downloaded items.  Thats when we created the suffix option.  This worked by allowing the user to create one "master" script that would:

1.  Call Podget with suffix enabled to download new items.
2.  Search download directories for files with the suffix.
3.  For the files it found, it would run any desired post-processing and then remove the suffix.

Then the 'master' script could get one crontab assignment.

For the second (number-prefix), we have one option in place that nearly accomplishes it.  For a feed if you enable the OPT_FILENAME_RENAME_MDATE, then it renames every downloaded file so it is prefixed with the last 'modification date' of the file.  Now not every server gives us an actual modification date and in those cases files are prefixed with the date/time that they were downloaded.

Let me clarify with an example, lets say I have a feed with OPT_FILENAME_RENAME_MDATE enabled and it downloads two items today.  And lets assume that the server does not give us a modification date.  What happens?

1.  Podget downloads first file (named filename.mp3).
2.  After downloading it, the OPTION causes it to be renamed 20170207_08h55m_filename.mp3
3.  Podget downloads the second file (also named filename.mp3).
4.  After downloading it, the OPTION causes it to be renamed 20170207_08h56m_filename.mp3

If the server does pass down a valid modification date for each file then that date is used for the prefix of the filename.

There is one minor issue with this method that can occur when the server does not give us a modification date. When files have the same name and your connection is fast enough or the files are small enough to be downloaded in the same minute then we might run into an issue renaming the files.  The simplest fix for this would be to extend the time stamp include a seconds part but there has not been any requests for it.

Now it is possible that the prefix created by OPT_FILENAME_RENAME_MDATE is longer than you would like but the easiest way to address that might be a combination of using a suffix and a little post-processing to convert the date used to a simpler number.  That script would need to find the largest number already used, then taking the new files (with suffix) in the order of MDATE and rename them to replace the date with a incrementing number and remove the suffix.

We have one other option that I've been experimenting with.  If you look in the SCRIPTS/v0.8.3 directory. you will find a script called podget_update_playlists,sh.  This script is meant to be run after podget and creates a full playlist for each feed.  It orders that playlist by modification dates without changing the filenames.  It basically works by taking each feed directory and listing items (ls -1tr) in reverse order of the modification date (oldest first) then adding them to a playlist.

Now you may need to download the DEV branch of Podget to get this script as it is just something I'm working on.  Eventually I would like to find a way to integrate it within Podget but so far I've run into a few minor issues that make that difficult.  

So thats what we have available already.  Do these fit your needs or is there something I've missed?

**Comment by lardconcepts** [comment]
Hi Dave,

Many thanks - I think your first suggestion is actually simplest and I wasn't thinking laterally enough!

Run podget, search files suffixed xxxx for example, and then process. Here's something I just found on StackOverflow and tweaked:

`ls *xxxx*.mp3 | cat -n | while read n f; do mv "$f" "$n-$f"; done`

Working out how to strip the suffix might require a little more SO action (my bash is rusty) but I think I have the idea in principle?! 👍 Thanks.
