### ISSUE TITLE
"DEBUG: unbound variable" warning

### ISSUE THREAD

**Issue by willemw12** [dvehrs/podget#3]
podget 0.7.10 from SourceForge (https://aur.archlinux.org/packages/podget).

    $ podget --create-config test1
    podget
      Installing default user configuration file in /home/willem/.podget/test1

    Closing session/usr/bin/podget: line 571: DEBUG: unbound variable

**Comment by dvehrs** [comment]
OK, this is embarrassing.  ;-)

It highlights an oversight in my testing checklists, but its a good catch and it's now been fixed in version 0.7.11 with a default value for the DEBUG variable being set early enough that it will be available for all functions.

Thanks Willem!
