### ISSUE TITLE
GnuTLS: A TLS packet with unexpected length was received

### ISSUE THREAD

**Issue by benpollinger** [dvehrs/podget#34]
Hello, I'm getting this error with some feeds, e.g. https://rss.acast.com/griefcast

```
GnuTLS: A TLS packet with unexpected length was received
Unable to establish SSL connection
```

Any thoughts?

**Comment by dvehrs** [comment]
OK, I ran a test on this feed and I'm not getting any errors here.   Was it something on their end that they fixed?

Now I only download the most recent 2 items in the feed so if the error occurs farther back than that, I will need to run more tests.

**Comment by benpollinger** [comment]
Thanks for the reply. I think it's a wider problem in my system as I get the same error with wget.

I installed podget on another machine and can't reproduce the error.

Thanks for checking this out.
