### ISSUE TITLE
Downloading podcasts from iTunes URLs

### ISSUE THREAD

**Issue by darcyrush** [dvehrs/podget#36]
I'm struggling to understand the format of the URL for itunes podcast feeds. I am using feedflipper to find rss feeds but it seems podget should be capable of using itunes URLs seeing that `FILENAME_FORMATFIX10` exists?

    https://itunes.apple.com/us/podcast/the-muay-thai-guys-podcast/id1018109852?mt=2 muay-thai The Muay Thai Guys

Just returns

    2017-12-01 17:16:53 URL:https://itunes.apple.com/us/podcast/muay-thai-guy-podcast/id636798781?mt=2 [531368] -> "-" [1]
      No enclosures in feed: https://itunes.apple.com/us/podcast/muay-thai-guy-podcast/id636798781?mt=2

Am I using the correct URL?

**Comment by dvehrs** [comment]
Apple iTunes and SoundCloud do things that are not compatible with simple RSS or Atom Feed aggregators like Podcast.  So basically to use these feeds we need to use a service that tells us where to find a feed for that show we can use.

In this case, the Muay Thai feed that iTunes provides does not include enclosure tags so we cannot use it in Podget.  However if we paste the iTunes feed URL into http://getrssfeed.com/ then we get the URL http://feeds.feedburner.com/TMTGpodcast that does have enclosures and should be usable by Podget.  

Hopefully this works, let  me know if you have any other issues.

Dave
