### ISSUE TITLE
Shortening long file names?

### ISSUE THREAD

**Issue by adam-funk** [dvehrs/podget#44]
Something has changed at Car Talk and I'm now getting these errors:

serverlist entry:

    http://www.npr.org/rss/podcast.php?id=510208             Car_Talk Car_Talk

entries in errors file:

    https://play.podtrac.com/npr-510208/npr.streaming.adswizz.com/anon.npr-podcasts/podcast/510208/710566189/npr_710566189.mp3?awCollectionId=510208&awEpisodeId=710566189&orgId=1&d=3273&p=510208&story=710566189&t=podcast&e=710566189&size=0&ft=pod&f=510208
    https://play.podtrac.com/npr-510208/npr.streaming.adswizz.com/anon.npr-podcasts/podcast/510208/708321428/npr_708321428.mp3?awCollectionId=510208&awEpisodeId=708321428&orgId=1&d=3222&p=510208&story=708321428&t=podcast&e=708321428&size=0&ft=pod&f=510208

error messages while running podget:

    /home/adam/Music/podget/Car_Talk/Car_Talk/npr_710566189_awCollectionId_510208_awEpisodeId_710566189_orgId_1_d_3273_p_510208_story_710566189_t_podcast_e_710566189_size_0_ft_pod_f_510208.mp3: File name too long
    /home/adam/Music/podget/Car_Talk/Car_Talk/npr_708321428_awCollectionId_510208_awEpisodeId_708321428_orgId_1_d_3222_p_510208_story_708321428_t_podcast_e_708321428_size_0_ft_pod_f_510208.mp3: File name too long

A way to automatically shorten filenames would be handy.

Thanks (great program --- I've been using it for years)

**Comment by dvehrs** [comment]
OK,  I tested this URL on version of podget from the DEV branch on my system and it appears to shorten the filenames if you have FILENAME_FORMATFIX9 enabled in your ~/.podget/podgetrc file.  It removes everything after the first ? in a filename.  So I end up with two files named npr_710566189.mp3 and npr_708321428.mp3.  Can you verify if FILENAME_FORMATFIX9 is enabled in your configuration then clear the items from the 'done' logfile and retry downloading them (or use the --force option to force a redownload)?  

Thanks!  It's good to know that there are still people out there using podget.

**Comment by adam-funk** [comment]
Sorry, I did not see that option! I'll test it today.

**Comment by adam-funk** [comment]
It turns out I have that enabled:

```
$ grep FORMATFIX .podget/podgetrc
#                                   Podget's FILENAME_FORMATFIX options unneeded.
FILENAME_FORMATFIX=1
FILENAME_FORMATFIX2=1
FILENAME_FORMATFIX3=1
FILENAME_FORMATFIX4=0
FILENAME_FORMATFIX5=1
FILENAME_FORMATFIX6=1
FILENAME_FORMATFIX7=1
# be used in conjunction with FILENAME_FORMATFIX4.
FILENAME_FORMATFIX8=1
FILENAME_FORMATFIX9=1
FILENAME_FORMATFIX10=1
```

but I'm using the 0.8.5-1 Ubuntu package.  I see that the dev branch has a commit marked "Fixes to Filename_FormatFix9", so I'll try that and report back.

**Comment by adam-funk** [comment]
Yes, it worked fine in the dev version.
Thanks!

**Comment by dvehrs** [comment]
Ok, so we know it will work in the next version.   

Thanks for the report!
