### ISSUE TITLE
Set filename based on episode date and title from rss feed

### ISSUE THREAD

**Issue by SimonGr3dal** [dvehrs/podget#46]
I think this could be a cool option to have because more and more podcasts are hosted places where the actual filename is just some sort of hash or GUID string and it is useless for sorting or identifying episodes.

**Comment by dvehrs** [comment]
While this sounds like a simple thing to do, I'm not sure it is given the way podget extracts the URLs from the feed file.  For RSS feeds, it looks for an enclosure tag and gets the URL= portion of it.  It's simple and efficient.  To get the title text from the feed would be challenging.  If anyone has any ideas on how to do this, I'm open to suggestions.

As for tagging a file with the date.  I would suggest using the OPT_FILENAME_RENAME_MDATE feed option, which prefixes the FILENAME with the last modification date of the file like so YYYYMMDD_HHhMMm_FILENAME.  This gives us a nice sort-able file name that looks like 20200224_15h33m_FILENAME (to use the today's date).  One warning when using this option, it has slightly different effects depending on the server you download from.  Some servers give you the file with the actual last modification date and so it will be tagged appropriately.  Other servers do not give you the actual last modification date and so the file will be tagged with the date & time when it was downloaded.  This might sound bad but it still results in an easily searchable name so it's not horrible.

**Comment by SimonGr3dal** [comment]
I did take a quick look at the script after I posted the issue and quickly realized that it probably wouldn't be easy or simple to do even if I was a lot more intimate with the code.

So I decided to try and make it myself in Python which has some nice libraries for that kind of thing.
https://github.com/SimonGr3dal/py-podcatcher/blob/master/pypodcatcher.py

**Comment by dvehrs** [comment]
Good Luck!
