### ISSUE TITLE
"File name too long" error from *Wait Wait... Don't Tell Me*

### ISSUE THREAD

**Issue by ph1l** [dvehrs/podget#48]
I just noticed this error:

```
Category: Audio                Name: NPR-Wait_Wait..._Dont_Tell_Me               
/home/elektron/podcast/Audio/NPR-Wait_Wait..._Dont_Tell_Me/20200502_waitwait_wwdtmpodcast200502-db024d89-d0de-433a-aa90-c6d2f58fa35b-c3642499-2b18-4d61-a11a-318e24223633_awCollectionId_344098539_awEpisodeId_847820014_orgId_1_d_2995_p_344098539_story_847820014_t_podcast_e_847820014_size_47815094_ft_pod_f_344098539.mp3: File name too long
/home/elektron/podcast/Audio/NPR-Wait_Wait..._Dont_Tell_Me/20200404_waitwait_wwdtmpodcast200404-436aa9ca-de7c-4bb0-8825-8ccc017ac0e4-6249b48b-feb0-408a-9ae1-cb50051b5d30_awCollectionId_344098539_awEpisodeId_827208523_orgId_1_d_2948_p_344098539_story_827208523_t_podcast_e_827208523_size_47075923_ft_pod_f_344098539.mp3: File name too long
/home/elektron/podcast/Audio/NPR-Wait_Wait..._Dont_Tell_Me/20200314_waitwait_wwdtmpodcast200314-f6e3b07f-8282-4c56-8523-57137792ecf3-3df9f14c-ba8b-4e38-963e-43a596421138_awCollectionId_344098539_awEpisodeId_815699189_orgId_1_d_2965_p_344098539_story_815699189_t_podcast_e_815699189_size_47335297_ft_pod_f_344098539.mp3: File name too long
/home/elektron/podcast/Audio/NPR-Wait_Wait..._Dont_Tell_Me/20200307_waitwait_wwdtmpodcast200307-d36f78db-6821-4420-a239-61ca2baf159b-116ac5cb-4e24-4956-b8b7-ec9bac8d1f72_awCollectionId_344098539_awEpisodeId_813129040_orgId_1_d_2956_p_344098539_story_813129040_t_podcast_e_813129040_size_47191015_ft_pod_f_344098539.mp3: File name too long
```

related to this rss feed:
```https://feeds.npr.org/344098539/podcast.xml Audio NPR-Wait_Wait..._Dont_Tell_Me```

**Comment by dvehrs** [comment]
OK, this is interesting.  I just attempted to download this feed and did not have a problem with any filename lengths.  However I  did notice a difference in filenames that are being used for my downloads and what you get.  

For example, you report:  
20200502_waitwait_wwd                                                                                           
tmpodcast200502-db024d89-d0de-433a-aa90-c6d2f58fa35b-c3642499-2b18-4d61-a11a-318                                                                                           
e24223633_awCollectionId_344098539_awEpisodeId_847820014_orgId_1_d_2995_p_344098                                                                                           
539_story_847820014_t_podcast_e_847820014_size_47815094_ft_pod_f_344098539.mp3

I got:
05_20200502_waitwait_wwdtmpodcast200502-db024d89-d0de-433a-aa90-c6d2f58fa35b-c3642499-2b18-4d61-a11a-318e24223633.mp3

What the feed lists for the file:
https://play.podtrac.com/npr-344098539/edge1.pod.npr.org/anon.npr-podcasts/podcast/npr/waitwait/2020/05/20200502_waitwait_wwdtmpodcast200502-db024d89-d0de-433a-aa90-c6d2f58fa35b-c3642499-2b18-4d61-a11a-318e24223633.mp3?awCollectionId=344098539&amp;awEpisodeId=847820014&amp;orgId=1&amp;d=2995&amp;p=344098539&amp;story=847820014&amp;t=podcast&amp;e=847820014&amp;size=47815094&amp;ft=pod&amp;f=344098539

Now what we can see is that my filename is much shorter than yours and that yours includes most of the options that come after the ? in the URL but has moved them to be before the MP3.    I believe this is related to one of the FILENAME_FORMATFIX options although I am unsure of which one.  I had all but FILENAME_FORMATFIX3 enabled but even enabling it is not producing the same filename.   Which options do you have enabled and which disabled?  

This might take some more testing....

Dave

**Comment by ph1l** [comment]
Oh, and To be clear, I'm using the debian package: `0.8.5-1`

**Comment by ph1l** [comment]
```
elektron@x200:~$ cat ~/.podget/podgetrc  | grep -v ^# | grep -v ^$
CONFIG_SERVERLIST=serverlist
DIR_LIBRARY=/home/elektron/podcast
LOG_FAIL=errors
LOG_COMPLETE=done
WGET_BASEOPTS="-c -nH"
MOST_RECENT=0
FORCE=0
CLEANUP=1
CLEANUP_DAYS=90
MIN_SPACE=614400
NO_PLAYLIST=1
PLAYLIST_NAMEBASE=New-
DATE_FORMAT=+%F
ASX_PLAYLIST=0
FILENAME_BADCHARS="\`~!#$^&=+{}*[]:;\"'<>?|\\"
FILENAME_REPLACECHAR=_
FILENAME_FORMATFIX=1
FILENAME_FORMATFIX2=1
FILENAME_FORMATFIX3=1
FILENAME_FORMATFIX4=0
FILENAME_FORMATFIX5=1
FILENAME_FORMATFIX6=1
FILENAME_FORMATFIX7=1
FILENAME_FORMATFIX8=1
FILENAME_FORMATFIX9=1
FILENAME_FORMATFIX10=1
```

**Comment by dvehrs** [comment]
OK.  I've set my FILENAME options to match yours and I'm using version 0.8.6-1 which should be close enough for testing.

FILENAME_FORMATFIX=1
FILENAME_FORMATFIX2=1
FILENAME_FORMATFIX3=1
FILENAME_FORMATFIX4=0
FILENAME_FORMATFIX5=1
FILENAME_FORMATFIX6=1
FILENAME_FORMATFIX7=1
FILENAME_FORMATFIX8=1
FILENAME_FORMATFIX9=1
FILENAME_FORMATFIX10=1

That did remove the leading '05_' off my filenames.  So we are closer to determining why it happens.

However I am still getting relatively short filenames without the additional bits added in before the MP3.   Now the 4 filenames you report are longer than the others but still short enough that they do not trigger a file length issue.  

I'm wondering if there was a feed issue that they have since corrected and that's why we're not seeing it now.  Can you try to redownload them to see if the issue is still happening?

Set your serverlist to only have this feed enabled then run:  podget -vvvv --force

This will run podget at near its highest verbosity hopefully that can give us a hint of what is going on.

After it runs, find the download section for the 20200502 file and paste it in here. 

Thanks,

Dave

**Comment by ph1l** [comment]
```
elektron@x200:~$ grep too\ long /tmp/podget.log
/home/elektron/podcast/Audio/NPR-Wait_Wait..._Dont_Tell_Me/20200502_waitwait_wwdtmpodcast200502-db024d89-d0de-433a-aa90-c6d2f58fa35b-c3642499-2b18-4d61-a11a-318e24223633_awCollectionId_344098539_awEpisodeId_847820014_orgId_1_d_2995_p_344098539_story_847820014_t_podcast_e_847820014_size_47815094_ft_pod_f_344098539.mp3: File name too long
/home/elektron/podcast/Audio/NPR-Wait_Wait..._Dont_Tell_Me/20200404_waitwait_wwdtmpodcast200404-436aa9ca-de7c-4bb0-8825-8ccc017ac0e4-6249b48b-feb0-408a-9ae1-cb50051b5d30_awCollectionId_344098539_awEpisodeId_827208523_orgId_1_d_2948_p_344098539_story_827208523_t_podcast_e_827208523_size_47075923_ft_pod_f_344098539.mp3: File name too long
/home/elektron/podcast/Audio/NPR-Wait_Wait..._Dont_Tell_Me/20200314_waitwait_wwdtmpodcast200314-f6e3b07f-8282-4c56-8523-57137792ecf3-3df9f14c-ba8b-4e38-963e-43a596421138_awCollectionId_344098539_awEpisodeId_815699189_orgId_1_d_2965_p_344098539_story_815699189_t_podcast_e_815699189_size_47335297_ft_pod_f_344098539.mp3: File name too long
/home/elektron/podcast/Audio/NPR-Wait_Wait..._Dont_Tell_Me/20200307_waitwait_wwdtmpodcast200307-d36f78db-6821-4420-a239-61ca2baf159b-116ac5cb-4e24-4956-b8b7-ec9bac8d1f72_awCollectionId_344098539_awEpisodeId_813129040_orgId_1_d_2956_p_344098539_story_813129040_t_podcast_e_813129040_size_47191015_ft_pod_f_344098539.mp3: File name too long
```
[podget.log](https://github.com/dvehrs/podget/files/4794992/podget.log)

**Comment by dvehrs** [comment]
OK, we can definitely see that it is being changed by Podget.  Now we need to see which format fix is doing it.  This will take another run with even more verbosity enabled.  This time we're going for full debug output.

If you had 0.8.6 then you could just run:  DEBUG=1 podget -vvvv --force

That may still work but generally for older versions you had to enable the DEBUG setting in your podgetrc file.  I'd recommend enabling it there and then run:  podget -vvvv --force

In particular we are looking for the section for the 20200502 file that looks like
ORIGINAL FILENAME:
DEBUG -- FILENAME FORMAT(#) FIXED:
MODIFIED FILENAME:

The part we care about will be the #.  It will tell us where the filename is being modified.

If I had to bet, I'd bet on it being FILENAME_FORMATFIX9.  There were a couple of fixes to it for 0.8.6.   If you like to upgrade to that version, you can either download the master branch from Github and manually install it.  Or if you are running Debian or Ubuntu, you can download a deb package from:  https://sourceforge.net/projects/podget/files/podget/podget-0.8.6/

Dave

**Comment by ph1l** [comment]
```
DEBUG -- Clear File Vars

ORIGINAL FILENAME:      20200502_waitwait_wwdtmpodcast200502-db024d89-d0de-433a-
aa90-c6d2f58fa35b-c3642499-2b18-4d61-a11a-318e24223633.mp3?awCollectionId=344098539&awEpisodeId=847820014&orgId=1&d=2995&p=344098539&story=847820014&t=podcast&e=847820014&size=47815094&ft=pod&f=344098539
DEBUG -- FILENAME FORMAT FIXED: 20200502_waitwait_wwdtmpodcast200502-db024d89-d0de-433a-aa90-c6d2f58fa35b-c3642499-2b18-4d61-a11a-318e24223633?awCollectionId=344098539&awEpisodeId=847820014&orgId=1&d=2995&p=344098539&story=847820014&t=podcast&e=847820014&size=47815094&ft=pod&f=344098539.mp3
MODIFIED FILENAME:      20200502_waitwait_wwdtmpodcast200502-db024d89-d0de-433a-aa90-c6d2f58fa35b-c3642499-2b18-4d61-a11a-318e24223633_awCollectionId_344098539_awEpisodeId_847820014_orgId_1_d_2995_p_344098539_story_847820014_t_podcast_e_847820014_size_47815094_ft_pod_f_344098539.mp3
Downloading 20200502_waitwait_wwdtmpodcast200502-db024d89-d0de-433a-aa90-c6d2f58fa35b-c3642499-2b18-4d61-a11a-318e24223633_awCollectionId_344098539_awEpisodeId_847820014_orgId_1_d_2995_p_344098539_story_847820014_t_podcast_e_847820014_size_47815094_ft_pod_f_344098539.mp3 from https://play.podtrac.com/npr-344098539/edge1.pod.npr.org/anon.npr-podcasts/podcast/npr/waitwait/2020/05
/home/elektron/podcast/Audio/NPR-Wait_Wait..._Dont_Tell_Me/20200502_waitwait_wwdtmpodcast200502-db024d89-d0de-433a-aa90-c6d2f58fa35b-c3642499-2b18-4d61-a11a-318e24223633_awCollectionId_344098539_awEpisodeId_847820014_orgId_1_d_2995_p_344098539_story_847820014_t_podcast_e_847820014_size_47815094_ft_pod_f_344098539.mp3: File name too long
```

**Comment by ph1l** [comment]
Seems like updating podget from unstable fixed it!

**Comment by dvehrs** [comment]
Excellent!

**Comment by ph1l** [comment]
Love the program. Thanks!

**Comment by dvehrs** [comment]
I'm going to leave this open for a bit just in case there are any new issues or if someone with the same problem is looking for a fix.  

Thanks for the report!

Dave
