### ISSUE TITLE
HPR podcast will not download

### ISSUE THREAD

**Issue by Kwisher** [dvehrs/podget#51]
Hello,

Seems there is a new download issue with the HPR podcast that has worked for years. The files quit downloading a few days ago so when I looked at their website I found new RSS links. After inserting the new code into my podget server list, it will still not d/l files. I looked in the log files for errors but found none. I loaded the RSS link into the Linux app Rhythmbox and the new link works. Please submit any other info you need from my system and I will be happy to provide it.

Also found the same issue with LinuxLugCast podcast:
https://linuxlugcast.com/

Reminder: You provided a link to your latest podget version in my last issue/ticket #47 and I'm still running it on Ubuntu 20.04.

HPR main website:
https://hackerpublicradio.org/

New RSS link:
http://hackerpublicradio.org/hpr_ogg_rss.php

Old RSS link:
http://hackerpublicradio.org/hpr_rss.php Podcasts HPR

Thank you for your great app!!

**Comment by dvehrs** [comment]
OK. you got lucky and caught me on a free morning.  A few days later and this would have to wait a bit.

All the feeds tested OK for me.  Only trick was finding the subscribe URL for linuxlugcast.  

This is was in my test serverlist:
http://hackerpublicradio.org/hpr_ogg_rss.php KWisher HPR-New
http://hackerpublicradio.org/hpr_rss.php KWisher HPR-Old
http://feeds.feedburner.com/linuxlugcast/dBDY KWisher LinuxLUGcast

The HPR feeds had episodes for the last two weeks and I got them in both OGG and MP3.   The linuxlugcast had episodes 147-156.  

If you're still having difficulty downloading these files, I would suggest increasing the verbosity of podget to see if it is reporting any issues.

Like so:  podget -vvvv  

Good Luck,
Dave

**Comment by Kwisher** [comment]
I will have to setup a podget test on a work PC to confirm it's my personal issue. Looks like it is since all 3 feeds work for you :)

I will report back soon.

**Comment by dvehrs** [comment]
New release out and its working for me.  If you have any issues, try with version 0.8.7.

Good Luck!

Dave
