### ISSUE TITLE
Podget cleanup by date fails with errors under OSX

### ISSUE THREAD

**Issue by scottmeup** [dvehrs/podget#52]
Podget gives the following error under OSX 10.10.5 . 

```
-------------------------------------------------
Cleanup old tracks.
date: illegal time format
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]

Error:
  Script:         podget
  At line:        2831
  Exit Status:    1

Context:
2828            CLEANUP_SECONDS=$((CLEANUP_DAYS*86400))
2829            # Convert CLEANUP_SECONDS to date in seconds from unix epoch before midnight last night.
2830            # This works with uniform whole days and isn't subject to when the cleanup is run.
2831 >>>        DATE_CLEAN2=$(($(date +%s --date 0:00)-CLEANUP_SECONDS))
2832            for FILE in ${FILELIST} ; do
2833                if [[ "${FILE##/*/}" =~ ^${PLAYLIST_NAMEBASE}* ]]; then
2834                    # Compare global playlist file modification date with DATE_CLEAN2.  If file modification date is newer than

Closing session and removing lock file.
```
I suspect all releases of OSX / MacOS would experience this issue as OSX's built in date and stat commands have different syntax from gnudate and gnustat.

I've worked around the issue by installing homebrew (https://brew.sh/) , and then running 
```
brew install coreutils
ln -s /opt/local/bin/gdate /opt/local/bin/date
ln -s /opt/local/bin/gstat /opt/local/bin/stat
```

and making sure the path is properly set in the cron job:

`0 * * * * PATH=/opt/local/bin/:/usr/local/bin:$PATH /usr/local/bin/podget`

&nbsp;

Podget runs without error after following the steps above, as well as ensuring the minimum required versions of bash, gsed and gexpr are installed and properly referenced by path variables in the cron job.

Cheers - Scott.

**Comment by dvehrs** [comment]
Nice diagnosis!  That's exactly what I suspected because the BSDs require gdate and gstat (or gnustat). 

I've added basic checks for gdate and gstat in the dev branch of Podget, so you might not need the links anymore if you upgrade to it.

I've also expanded the INSTALL file to include installing gdate and gstat.

Hopefully I got all the filenames right.

Thanks,

Dave

**Comment by dvehrs** [comment]
Uploaded a new version (0.8.8) with checks for gdate and gstat on Mac OS.  Hopefully this works for everyone.

Dave
