### ISSUE TITLE
Support filename cleanup of m4a extension

### ISSUE THREAD

**Issue by omsai** [dvehrs/podget#64]
One of my RSS feeds changed their file extensions from mp3 to m4a, but the m4a file extension isn't currently recognized by the filename cleanup steps to strip the POST tag.  Therefore the `?...` following the m4a file extension is replaced with `_...` causing the extension to become part of the filename.  My portable media player, seeing no recognizable file extension, then hides the file on its filesystem.  The feed in particular is http://defendandpublish.libsyn.com/rss where up to episode 47 there are mp3 files which work fine, but episode 48 onward are m4a which is currently problematic.

**Comment by omsai** [comment]
It looks like regex pattern in condition that handles the `FILENAME_FORMATFIX6` needs to be updated perhaps from `.[gmopv34]` to `.[gmopv34a]`

**Comment by dvehrs** [comment]
Also, you may want to take a look at the Changelog file in the DEV branch.  I've added a potential comment for the next release for this fix.  Hopefully I haven't made any typos.

**Comment by omsai** [comment]
Thank you!  I tested that the new version 935d016 works well for me and your Changelog entry also looks good; thank you for the acknowledgement and for making and maintaining this excellent tool.
