### ISSUE TITLE
script speedup.sh has a zsh shebang and a ".sh" extension

### ISSUE THREAD

**Issue by m040601** [dvehrs/podget#77]
Thanks for the continued work on podget. Very appreciated. I use it with newsboat.

I was casually checking .sh shell scripts in my system using,

```
Name            : checkbashisms
Version         : 2.23.7-1
Description     : Debian script that checks for bashisms
URL             : https://tracker.debian.org/pkg/devscripts
Packager        : George Rawlinson <grawlinson@archlinux.org>
```

It warned me this,

```
script /usr/share/podget/scripts/v0.8.5/speedup.sh does not appear to be a /bin/sh script; skipping
```

And indeed, that /usr/share/podget/scripts/v0.8.5/speedup.sh,

```
#!/bin/zsh
# faster mp3 playback https://superuser.com/questions/519649/tool-to-bulk-speed-up-convert-an-audio-file
for i in $*;do
  ffmpeg -i $i -filter:a "atempo=1.6" -c:a libmp3lame -q:a 4 -vsync 2 ~/speedup/$i
done
```

Has a zsh shebang but is named with a .sh extension.

**Comment by dvehrs** [comment]
I don't think we should make any changes to this file for the following reasons:

- The .sh extension is merely a tool to aid the user.  The extension is not actually used by the system.  The system relies on the shebang to determine which shell to use.
- The .sh extension is fairly generic.  The file could be a dash script, a bash script, a tsch script or a zsh script.  The only time it really makes sense to use .zsh or .bash extensions is if we have a single script implemented in multiple ways and want to use a similar base name for them all.  
- In this case the script is only 5 lines long, one of which is the shebang and one a comment.  So even if a user does not have ZSH installed then it would be fairly easy to convert to another shell.
- This was a user submitted script.  As a general rule, I try to do as little as possible with user submissions.  Some changes may need to be made but I really try to avoid them to protect what has been shared.
- This script was included over five years ago.  I have not recently tested it but it would not surprise me that there have been changes to ffmpeg or zsh that may require tweaks, but I don't think that is what is important for this script.  I include these merely as ideas of what can be done and not as final solutions.  In a way it's not entirely dissimilar to using Podget with Newsboat.  That's not something I have done myself but it is good to hear that new ways to use Podget are still being found.

Thanks,
Dave
